sudo: required
services:
   - docker

before_install: 
   - docker build -t folamzz87/docker-react -f Dockerfile.dev .

script: 
   - docker run -e CI=true folamzz87/docker-react npm run test

deploy:
   provider: elasticbeanstalk
   region: "us-east-1"
   app: "react"
   env: "React-env"
   bucket_name: "elasticbeanstalk-us-east-1-733345126637"
   bucket_path: "react"
   on:
     branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY